### ISSUE TITLE
terneo: Error on device update!

### ISSUE THREAD

**Issue by profx5015** [Makave1i/terneo_thermostat#4]
Terneo frimware version: 2.5
Sometimes got such error:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
    await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/terneo/climate.py", line 159, in update
    self.thermostat.update()
  File "/config/custom_components/terneo/thermostat.py", line 231, in update
    data = self.status()
  File "/config/custom_components/terneo/thermostat.py", line 121, in status
    r = self.post(json={"cmd": 4})
  File "/config/custom_components/terneo/thermostat.py", line 109, in post
    content = r.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

HA version: 2021.15

**Comment by Floppik** [comment]
Same here
Logger: homeassistant.components.climate
Source: custom_components/terneo/thermostat.py:109
Integration: Климат (documentation, issues)
First occurred: 15:34:58 (1 occurrences)
Last logged: 15:34:58

terneo: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 365, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 482, in async_device_update
    await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/terneo/climate.py", line 159, in update
    self.thermostat.update()
  File "/config/custom_components/terneo/thermostat.py", line 231, in update
    data = self.status()
  File "/config/custom_components/terneo/thermostat.py", line 121, in status
    r = self.post(json={"cmd": 4})
  File "/config/custom_components/terneo/thermostat.py", line 109, in post
    content = r.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Makave1i** [comment]
I'm sorry, last months overloaded with the main job and do not have enough time to investigate and fix that. As I can see, terneo sometimes returns wrong data, probably enough to wrap this line `content = r.json()` in `try/except`. Will be very appreciated if someone can make PR with that fix)
